### ISSUE TITLE
geometry columns are "not null" by default

### ISSUE THREAD

**Issue by michael-groble** [rgeo/activerecord-spatialite-adapter#2]
In contrast to the postgis adapter, given the following column definition:

```
  t.multi_polygon :region, srid: 3529
```

it incorrectly creates the column as not null.   Changing the column to 

```
  t.multi_polygon :region, srid: 3529, null: true
```

solves the problem, but it would be nice for this adapter to support the expected default behavior so the first version creates a nullable column.

**Comment by dazuma** [comment]
Fixed in release 0.4.1
